executor: cluster-generic
cluster-generic-submit-cmd:
  SMK_RULE_DIR=logs/`date +"%y-%m-%d"`/{rule} &&
  SMK_WILDCARDS=`echo -n '{wildcards}' | sed -e 's#/#-#g'` &&
  SMK_SLURM_EXTRA=`echo -n '{resources.slurm_extra}' | sed -e 's/%/:/g'` &&
  mkdir -p $SMK_RULE_DIR &&
  sbatch
    --job-name={rule}:{wildcards}
    --ntasks={threads}
    --mem-per-cpu=`expr {resources.mem_mb} / {threads}`
    --tmp={resources.disk_mb}
    --time={resources.runtime}
    --output=$SMK_RULE_DIR/{rule}:$SMK_WILDCARDS-%j.txt
    $SMK_SLURM_EXTRA
    --parsable
cluster-generic-status-cmd: status-sacct.sh
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 1000
default-resources:
  runtime: 1h
  mem_mb: 1024
  disk_mb: 1024
  slurm_extra: "''"
restart-times: 3
#https://github.com/snakemake/snakemake/issues/3019
max-jobs-per-second: 200
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cores: 64 # https://github.com/snakemake/snakemake/issues/2997
