executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --job-name=smk-{rule}-{wildcards}
    --ntasks={threads}
    --mem-per-cpu=`expr {resources.mem_mb} / {threads}`
    --tmp={resources.disk_mb}
    --time={resources.runtime}
    --output=logs/{rule}/{rule}-{wildcards}-%j.txt
    $(echo -n '{resources.slurm_extra}' | sed -e 's/%3A/:/g')
    --parsable
cluster-generic-status-cmd: status-sacct.sh
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 50
default-resources:
- runtime=1h
- mem_mb=1024
- disk_mb=1024
- slurm_extra=''
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
